Allow gaudi to be invoked from within any project subdirectory. Add gaudi new (class|interface|enum) command

diff --git a/gaudi b/gaudi
--- a/gaudi
+++ b/gaudi
@@ -22,11 +22,8 @@ CLASSES_DIR="$BUILD_DIR/classes"
 GENERATED_DIR="$BUILD_DIR/generated-sources/javac"
 DEPENDENCIES_FILE="$BUILD_DIR/dependencies.lock"
 
-if test -f build-info.sh; then
-    . ./build-info.sh
-fi
-
 SELF="$0"
+INVOKED_IN_DIR="$(pwd)"
 
 case "$1" in
     init)
@@ -50,19 +47,6 @@ case "$1" in
             echo "}"
         ) > "$PACKAGE_DIR/Main.java"
         echo "MAIN_CLASS=$PACKAGE_NAME.Main" > $NAME/build-info.sh
-        ;;
-    resolve)
-        echo "Manual resolution is required: create $DEPENDENCIES_FILE file manually"
-        echo "dependencies.lock format is as follows:"
-        echo
-        echo ARTIFACT1_NAME ARTIFACT1_VERSION
-        echo ARTIFACT2_NAME ARTIFACT2_VERSION
-        echo ...
-        echo ARTIFACT_N_NAME ARTIFACT_N_VERSION
-        echo
-        echo "For example junit launcher can be specified like:"
-        echo
-        echo org.junit.platform.junit-platform-console-standalone 1.0.0
         ;;
     download)
         URL="$2"
@@ -106,191 +90,268 @@ case "$1" in
             flock "$RUNTIME_DIR/lock" "$SELF" download "$URL" "$ARTIFACT_FILE" && echo "$ARTIFACT_FILE"
         fi
         ;;
-    classpath)
-        if ! test -f $DEPENDENCIES_FILE; then
-            echo "WARNING: Classpath is empty: Does not exist: $DEPENDENCIES_FILE" >&2
-            exit 0
-        else
-            cat "$DEPENDENCIES_FILE" | (
-                CLASSPATH=""
-                while read ARTIFACT VERSION; do
-                    ARTIFACT_FILE="$($SELF artifact-file $ARTIFACT $VERSION)"
-                    if ! test "$?" -eq 0; then
+    *)
+        while ! test -f build-info.sh && ! test "$(pwd)" '=' "/"; do
+            case "$SELF" in
+                ./*)
+                    SELF="../$SELF"
+                    ;;
+                ../*)
+                    SELF="../$SELF"
+                    ;;
+            esac
+            cd ..
+        done
+
+        if ! test -f build-info.sh; then
+            echo "build-info.sh not found" >&2
+            exit 2
+        fi
+
+        . ./build-info.sh
+
+        case "$1" in
+            new)
+                cd "$SOURCES_DIR"
+                SOURCES_DIR="$(pwd)"
+                PACKAGE=""
+                case "$INVOKED_IN_DIR" in
+                    $SOURCES_DIR*)
+                        PACKAGE=$(echo "$INVOKED_IN_DIR" | awk -v "sources_dir=$SOURCES_DIR" '
+                            {
+                                gsub(/\//, ".");
+                                print substr($0, length(sources_dir) + 1, length($0) - length(sources_dir));
+                            }' | sed 's/^\.//g')
+                        ;;
+                    *)
+                        echo "invoked not in sources dir" >&2
                         exit 2
-                    fi
-                    if test -n "$CLASSPATH"; then
-                       CLASSPATH="$CLASSPATH:$ARTIFACT_FILE"
-                    else
-                       CLASSPATH="$ARTIFACT_FILE"
-                    fi
-                done
-                echo "$CLASSPATH"
-            )
-        fi
-        ;;
-    compile-classpath)
-        CLASSPATH="$("$SELF" classpath)"
-        RESULT="$?"
-        if ! test "$RESULT" -eq 0; then
-            exit "$RESULT"
-        else
-            if test -d "$COMPILE_ONLY_RESOURCES_DIR"; then
-                if test -n "$CLASSPATH"; then
-                    CLASSPATH="$COMPILE_ONLY_RESOURCES_DIR:$CLASSPATH"
-                else
-                    CLASSPATH="$COMPILE_ONLY_RESOURCES_DIR"
-                fi
-            fi
-            echo "$CLASSPATH"
-        fi
-        ;;
-    compile)
-        CLASSPATH="$("$SELF" compile-classpath)"
-        RESULT="$?"
-        if ! test "$RESULT" -eq 0; then
-            exit "$RESULT"
-        else
-            if ! test -d "$SOURCES_DIR"; then
-                echo "Sources directory does not exist: $SOURCES_DIR" >&2
-                exit 2
-            fi
-
-            echo "======================================================================================"
-            echo "                                     COMPILING                                        "
-            echo "======================================================================================"
-            echo
-
-            SOURCES="$(find "$SOURCES_DIR" -type f -name '*.java' | sort)"
-            RESOURCES=""
-            if test -d "$RESOURCES_DIR"; then
-                RESOURCES="$(find "$RESOURCES_DIR" -type f | sort)"
-            fi
-            for D1 in "$RESOURCES_DIR" "$RUN_ONLY_RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
-                for D2 in "$RESOURCES_DIR" "$RUN_ONLY_RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
-                    if test "$D1" '!=' "$D2" && test -d "$D1" && test -d "$D2"; then
-                        LIST1=$(mktemp)
-                        LIST2=$(mktemp)
-                        BEFORE_EXIT=(rm "$LIST1" "$LIST2")
-                        find "$D1" -type f -printf '%P\n' | sort > "$LIST1"
-                        find "$D2" -type f -printf '%P\n' | sort > "$LIST2"
-
-                        if test "$(join "$LIST1" "$LIST2" | wc -l)" -gt 0; then
-                            echo "ERROR: You have same entries in $RESOURCES_DIR and $COMPILE_ONLY_RESOURCES_DIR." >&2
-                            echo "       Every resource should be present in one and only one directory" >&2
-                            echo >&2
-                            join "$LIST1" "$LIST2" | sed 's/^/        /g'
-                            "${BEFORE_EXIT[@]}"
-                            exit 2
-                        fi
-                        "${BEFORE_EXIT[@]}"
-                    fi
-                done
-            done
-
-            for D in "$RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
-                ANNOTATION_PROCESSOR_DISCOVERY_FILE="$META-INF/services/javax.annotation.processing.Processor"
-                if test -f "$D/$ANNOTATION_PROCESSOR_DISCOVERY_FILE"; then
-                    echo "ERROR: compilation is impossible with annotation processors service discovery file: $D/$ANNOTATION_PROCESSOR_DISCOVERY_FILE" >&2
-                    echo "       Move it to run time only resources directory for compilation to succeed: $RUN_ONLY_RESOURCES_DIR/$ANNOTATION_PROCESSOR_DISCOVERY_FILE" >&2
+                        ;;
+                esac
+                cd "$INVOKED_IN_DIR"
+                NAME="$3"
+                FILE="$NAME.java"
+                if test -f "$FILE"; then
+                    echo "Already exists: $FILE" >&2
                     exit 2
                 fi
-            done
-
-            FINGERPRINT="$(sha1sum $SOURCES $RESOURCES | sha1sum | awk '{print $1}')"
-            if test -f "$FINGERPRINT_FILE"; then
-                OLD_FINGERPRINT="$(cat "$FINGERPRINT_FILE")"
-                if test "$FINGERPRINT" '=' "$OLD_FINGERPRINT"; then
-                    cat "$JAVAC_OUT_FILE"
-                    cat "$JAVAC_ERR_FILE" >&2
-                    RESULT="$(cat "$JAVAC_RESULT_FILE")"
-                    echo
-                    echo
-                    echo
-                    exit "$RESULT"
+                case "$2" in
+                    class|interface|enum)
+                        (
+                            echo "package $PACKAGE;"
+                            echo
+                            echo "$2 $NAME {"
+                            echo "}"
+                        ) > "$FILE"
+                        ;;
+                    *)
+                        echo "Unsupported entity: $2" >&2
+                        echo "Use one of class, interface or enum" >&2
+                        exit 2
+                        ;;
+                esac
+                ;;
+            resolve)
+                echo "Manual resolution is required: create $DEPENDENCIES_FILE file manually"
+                echo "dependencies.lock format is as follows:"
+                echo
+                echo ARTIFACT1_NAME ARTIFACT1_VERSION
+                echo ARTIFACT2_NAME ARTIFACT2_VERSION
+                echo ...
+                echo ARTIFACT_N_NAME ARTIFACT_N_VERSION
+                echo
+                echo "For example junit launcher can be specified like:"
+                echo
+                echo org.junit.platform.junit-platform-console-standalone 1.0.0
+                ;;
+            classpath)
+                if ! test -f $DEPENDENCIES_FILE; then
+                    echo "WARNING: Classpath is empty: Does not exist: $DEPENDENCIES_FILE" >&2
+                    exit 0
+                else
+                    cat "$DEPENDENCIES_FILE" | (
+                        CLASSPATH=""
+                        while read ARTIFACT VERSION; do
+                            ARTIFACT_FILE="$($SELF artifact-file $ARTIFACT $VERSION)"
+                            if ! test "$?" -eq 0; then
+                                exit 2
+                            fi
+                            if test -n "$CLASSPATH"; then
+                               CLASSPATH="$CLASSPATH:$ARTIFACT_FILE"
+                            else
+                               CLASSPATH="$ARTIFACT_FILE"
+                            fi
+                        done
+                        echo "$CLASSPATH"
+                    )
                 fi
-                rm "$FINGERPRINT_FILE"
-            fi
-
-            rm -rf "$CLASSES_DIR"
-            rm -rf "$GENERATED_DIR"
-            mkdir -p "$CLASSES_DIR"
-            mkdir -p "$GENERATED_DIR"
-            if test -d "$RESOURCES_DIR"; then
-                for F in "$RESOURCES_DIR"/*; do
-                    if test -e "$F"; then
-                        cp -r "$F" "$CLASSES_DIR"
-                    fi
-                done
-            fi
-
-            javac \
-                -cp "$CLASSPATH" \
-                -sourcepath '' \
-                -encoding UTF-8 \
-                -source 8 \
-                -target 8 \
-                -Werror \
-                -Xlint:all \
-                -d "$CLASSES_DIR" \
-                -s "$GENERATED_DIR" \
-                    $SOURCES >"$JAVAC_OUT_FILE" 2>"$JAVAC_ERR_FILE"
-            RESULT="$?"
-            echo "$RESULT" > "$JAVAC_RESULT_FILE"
-            cat "$JAVAC_OUT_FILE"
-            cat "$JAVAC_ERR_FILE" >&2
-
-            if test -d "$RUN_ONLY_RESOURCES_DIR"; then
-                cp -r "$RUN_ONLY_RESOURCES_DIR"/* "$CLASSES_DIR"
-            fi
-            echo "$FINGERPRINT" > "$FINGERPRINT_FILE"
-
-            echo
-            echo
-            echo
-
-            exit "$RESULT"
-        fi
-        ;;
-    run-classpath)
-        CLASSPATH="$("$SELF" classpath)"
-        RESULT="$?"
-        if ! test "$RESULT" -eq 0; then
-            exit "$RESULT"
-        else
-            if test -n "$CLASSPATH"; then
-                CLASSPATH="$CLASSES_DIR:$CLASSPATH"
-            else
-                CLASSPATH="$CLASSES_DIR"
-            fi
-            echo "$CLASSPATH"
-        fi
-        ;;
-    run)
-        if test -z "$MAIN_CLASS"; then
-            echo MAIN_CLASS is not specified. Please specify main class in build-info.sh >&2
-            exit 2
-        else
-            $SELF compile && (
-                CLASSPATH="$("$SELF" run-classpath)"               
+                ;;
+            compile-classpath)
+                CLASSPATH="$("$SELF" classpath)"
                 RESULT="$?"
                 if ! test "$RESULT" -eq 0; then
                     exit "$RESULT"
                 else
+                    if test -d "$COMPILE_ONLY_RESOURCES_DIR"; then
+                        if test -n "$CLASSPATH"; then
+                            CLASSPATH="$COMPILE_ONLY_RESOURCES_DIR:$CLASSPATH"
+                        else
+                            CLASSPATH="$COMPILE_ONLY_RESOURCES_DIR"
+                        fi
+                    fi
+                    echo "$CLASSPATH"
+                fi
+                ;;
+            compile)
+                CLASSPATH="$("$SELF" compile-classpath)"
+                RESULT="$?"
+                if ! test "$RESULT" -eq 0; then
+                    exit "$RESULT"
+                else
+                    if ! test -d "$SOURCES_DIR"; then
+                        echo "Sources directory does not exist: $SOURCES_DIR" >&2
+                        exit 2
+                    fi
+
                     echo "======================================================================================"
-                    echo "                                     RUNNING                                          "
+                    echo "                                     COMPILING                                        "
                     echo "======================================================================================"
                     echo
 
-                    java -cp "$CLASSPATH" "$MAIN_CLASS"
+                    SOURCES="$(find "$SOURCES_DIR" -type f -name '*.java' | sort)"
+                    RESOURCES=""
+                    if test -d "$RESOURCES_DIR"; then
+                        RESOURCES="$(find "$RESOURCES_DIR" -type f | sort)"
+                    fi
+                    for D1 in "$RESOURCES_DIR" "$RUN_ONLY_RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
+                        for D2 in "$RESOURCES_DIR" "$RUN_ONLY_RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
+                            if test "$D1" '!=' "$D2" && test -d "$D1" && test -d "$D2"; then
+                                LIST1=$(mktemp)
+                                LIST2=$(mktemp)
+                                BEFORE_EXIT=(rm "$LIST1" "$LIST2")
+                                find "$D1" -type f -printf '%P\n' | sort > "$LIST1"
+                                find "$D2" -type f -printf '%P\n' | sort > "$LIST2"
 
+                                if test "$(join "$LIST1" "$LIST2" | wc -l)" -gt 0; then
+                                    echo "ERROR: You have same entries in $RESOURCES_DIR and $COMPILE_ONLY_RESOURCES_DIR." >&2
+                                    echo "       Every resource should be present in one and only one directory" >&2
+                                    echo >&2
+                                    join "$LIST1" "$LIST2" | sed 's/^/        /g'
+                                    "${BEFORE_EXIT[@]}"
+                                    exit 2
+                                fi
+                                "${BEFORE_EXIT[@]}"
+                            fi
+                        done
+                    done
+
+                    for D in "$RESOURCES_DIR" "$COMPILE_ONLY_RESOURCES_DIR"; do
+                        ANNOTATION_PROCESSOR_DISCOVERY_FILE="$META-INF/services/javax.annotation.processing.Processor"
+                        if test -f "$D/$ANNOTATION_PROCESSOR_DISCOVERY_FILE"; then
+                            echo "ERROR: compilation is impossible with annotation processors service discovery file: $D/$ANNOTATION_PROCESSOR_DISCOVERY_FILE" >&2
+                            echo "       Move it to run time only resources directory for compilation to succeed: $RUN_ONLY_RESOURCES_DIR/$ANNOTATION_PROCESSOR_DISCOVERY_FILE" >&2
+                            exit 2
+                        fi
+                    done
+
+                    FINGERPRINT="$(sha1sum $SOURCES $RESOURCES | sha1sum | awk '{print $1}')"
+                    if test -f "$FINGERPRINT_FILE"; then
+                        OLD_FINGERPRINT="$(cat "$FINGERPRINT_FILE")"
+                        if test "$FINGERPRINT" '=' "$OLD_FINGERPRINT"; then
+                            cat "$JAVAC_OUT_FILE"
+                            cat "$JAVAC_ERR_FILE" >&2
+                            RESULT="$(cat "$JAVAC_RESULT_FILE")"
+                            echo
+                            echo
+                            echo
+                            exit "$RESULT"
+                        fi
+                        rm "$FINGERPRINT_FILE"
+                    fi
+
+                    rm -rf "$CLASSES_DIR"
+                    rm -rf "$GENERATED_DIR"
+                    mkdir -p "$CLASSES_DIR"
+                    mkdir -p "$GENERATED_DIR"
+                    if test -d "$RESOURCES_DIR"; then
+                        for F in "$RESOURCES_DIR"/*; do
+                            if test -e "$F"; then
+                                cp -r "$F" "$CLASSES_DIR"
+                            fi
+                        done
+                    fi
+
+                    javac \
+                        -cp "$CLASSPATH" \
+                        -sourcepath '' \
+                        -encoding UTF-8 \
+                        -source 8 \
+                        -target 8 \
+                        -Werror \
+                        -Xlint:all \
+                        -Xdiags:verbose \
+                        -d "$CLASSES_DIR" \
+                        -s "$GENERATED_DIR" \
+                            $SOURCES >"$JAVAC_OUT_FILE" 2>"$JAVAC_ERR_FILE"
                     RESULT="$?"
+                    echo "$RESULT" > "$JAVAC_RESULT_FILE"
+                    cat "$JAVAC_OUT_FILE"
+                    cat "$JAVAC_ERR_FILE" >&2
+
+                    if test -d "$RUN_ONLY_RESOURCES_DIR"; then
+                        cp -r "$RUN_ONLY_RESOURCES_DIR"/* "$CLASSES_DIR"
+                    fi
+                    echo "$FINGERPRINT" > "$FINGERPRINT_FILE"
+
                     echo
                     echo
                     echo
+
                     exit "$RESULT"
                 fi
-            )
-        fi
+                ;;
+            run-classpath)
+                CLASSPATH="$("$SELF" classpath)"
+                RESULT="$?"
+                if ! test "$RESULT" -eq 0; then
+                    exit "$RESULT"
+                else
+                    if test -n "$CLASSPATH"; then
+                        CLASSPATH="$CLASSES_DIR:$CLASSPATH"
+                    else
+                        CLASSPATH="$CLASSES_DIR"
+                    fi
+                    echo "$CLASSPATH"
+                fi
+                ;;
+            run)
+                if test -z "$MAIN_CLASS"; then
+                    echo MAIN_CLASS is not specified. Please specify main class in build-info.sh >&2
+                    exit 2
+                else
+                    $SELF compile && (
+                        CLASSPATH="$("$SELF" run-classpath)"               
+                        RESULT="$?"
+                        if ! test "$RESULT" -eq 0; then
+                            exit "$RESULT"
+                        else
+                            echo "======================================================================================"
+                            echo "                                     RUNNING                                          "
+                            echo "======================================================================================"
+                            echo
+
+                            java -cp "$CLASSPATH" "$MAIN_CLASS"
+
+                            RESULT="$?"
+                            echo
+                            echo
+                            echo
+                            exit "$RESULT"
+                        fi
+                    )
+                fi
+                ;;
+        esac
         ;;
 esac
 
